zuul:
  routes:
    first:
      path: /first_*_*/**
      url: http://httpbin.org:80
#      strip-prefix: true
      

server:
  port: 8084
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"   
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true 
      sla:
        http:
          server:
            requests: 1ms, 5ms
logging:
  level:
    root: info 